- name: "Launch postgres container"
  docker_container:
    name: db
    image: postgres:11.2
    ports:
      - '5432:5432'
    # TODO check
    # volumes:
    #   - /private/var/lib/postgresql:/var/lib/postgresql



- name: Launch nginx container
  docker_container:
    name: nginx
    image:  nginx:1.15
    ports:
      - '80:80'
      - '443:443'
    # links:
    #   - web
    volumes:
      -  ./data/nginx:/etc/nginx/conf.d
