- name: "apt | Install docker driver"
  apt:
    pkg: ['python', 'python-docker']
    state: present

- name: "apt | Install rsync"
  apt:
    pkg: 'rsync'
    state: present
  when: is_prod

- name: "synchronize | ctfd files"
  synchronize:
    src: ../ctfd/
    dest: /opt/ctfd
    archive: false
    checksum: true
    delete: true
    compress: true
    recursive: true
    perms: true
  when: is_prod

- name: docker | Create network
  docker_network:
    name: ctfdnet

- name: "docker | Launch postgres container"
  docker_container:
    name: pgdb
    image: postgres:11.2
    ports:
      - '5432:5432'
    env:
      POSTGRES_USER: ctfd
      POSTGRES_PASSWORD: "{{ postgres_db_password }}"
    volumes:
      - /var/lib/postgresql
    networks:
      - name: ctfdnet

- name: docker | Build web container image
  docker_image:
    path: '{{ ctf_docker_build_path }}'
    name: web
    force: "{{ docker_force }}"

- name: docker | Start web container
  docker_container:
    name: web
    image: web
    ports:
      - '8000:8000'
    env:
      DATABASE_URL: 'postgresql+psycopg2://ctfd:{{ postgres_db_password }}@pgdb:5432/ctfd'
      SECRET_KEY: '{{ ctf_secret_key }}'
    volumes:
      - '{{ ctf_log_dir }}:/opt/CTFd/logs'
    networks:
      - name: ctfdnet
